### ISSUE TITLE
2week [ react ] Todo List / Movie Poster

### ISSUE THREAD

**Issue by iamyeongg** [SSUMC-6th/WEB_B#6]
- [ ]  핵심 키워드 정리 > 노션
- [ ]  react 개발 환경 셋팅
- 미션
  - [ ] Todo List / react 
  - [ ] Movie Poster영화 웹 구현
